### ISSUE TITLE
Cannot install on Mac with MultiMC

### ISSUE THREAD

**Issue by raulium** [jrbudda/Vivecraft_117#10]
It is impossible to select the MultiMC "directory" within the installer. On a Mac, MultiMC (and all it's subfolders, instances, etc) are located in the MultiMC.app file. The contents can be viewed via terminal, however navigating within the installer to the directory where the MultiMC.app file is located shows nothing.

Symlinks also do not seem to fix the issue.

**Comment by Techjar** [comment]
The text input for the file selection is supposed to be editable, so you can just paste the .app path that macOS's stupid file browser won't let you navigate into, but this change was lost in the 1.17 update. Will fix soon.
