### ISSUE TITLE
Installer not downloading as a program

### ISSUE THREAD

**Issue by Zumoshika** [jrbudda/Vivecraft_117#12]
When i download the file it downloads not as a program but as something you can open with winrar or whatever it means i cant actually launch the program. I tried to change it to anything i could for it to open but it simply doesnt work how do i fix this issue?

**Comment by TheTrueForce** [comment]
The installer comes as a jar file. That is a Java program. If it's opening in an archiver, you either do not have Java installed or it is not set up to open jar files.
The install that comes with Minecraft is not available to the rest of the system. You need a proper system-wide install of Java to run the installer.

**Comment by Techjar** [comment]
Run jarfix
