### ISSUE TITLE
Installer doesn't work with Launcher from Xbox Game Pass

### ISSUE THREAD

**Issue by epheph** [jrbudda/Vivecraft_117#15]
I launched Vivecraft for the first time with the Launcher from Xbox Game Pass app on Windows 10. The installer runs, but the profiles never appear in the launcher.

I poked around a bit and after trying to install 1.16 with "Forge" i realized that the launcher profile file being written to by Vivecraft installers is not the one being used by the launcher from Xbox app. The installer targets:

`launcher_profiles.json`

the launcher targets:
`launcher_profiles_microsoft_store.json`

I was able to get the integration working by [killing the launcher] and copying
`launcher_profiles_microsoft_store.json` to `launcher_profiles.json`, running the installer, then copying `launcher_profiles.json` back to `launcher_profiles_microsoft_store.json`

**Comment by jrbudda** [comment]
fixt
