### ISSUE TITLE
Broken Contextual Interact, Right Click Delay Broken & Not Present

### ISSUE THREAD

**Issue by SCAbruh** [jrbudda/Vivecraft_117#16]
Blocks that normally support contextual interact no longer seem to. Now it's only entities like item frames & animals.

Also, the option for right click delay is no longer present in controller options, and editing it through the files doesn't seem to work. This sucks because I constantly find myself placing blocks or casting a fishing rod twice on one input.

**Comment by Techjar** [comment]
yeah
