### ISSUE TITLE
[FR] option to disable "eat me"-pie ect.

### ISSUE THREAD

**Issue by Korbinbrandon** [jrbudda/Vivecraft_117#18]
I'd like to disable the spawning of the "eat me"-pie, "drink me"-water and other similar Items (if any) in my inventory.
I was unable to find such an option.

**Comment by fayer3** [comment]
with the latest alpha for vivecraft 1.17.1 you can do that, don't think there is an ingame option, but in `optionsviveprofiles.txt` set `disableFun` to `true`

**Comment by Korbinbrandon** [comment]
Sounds good enough for me. I had checked that file but was on an older version.
I set it to true and assume it will work.

**Comment by Techjar** [comment]
For the record, I also fixed the bug where they were appearing far too frequently.
