### ISSUE TITLE
Gpu competability

### ISSUE THREAD

**Issue by barrulik** [jrbudda/Vivecraft_117#4]
Hello there, can you add vivcraft support to intel gpus?

**Comment by TheTrueForce** [comment]
This is Intel's problem, not vivecraft's.
Their driver mungs the framebuffer format used by OpenGL VR applications.

**Comment by barrulik** [comment]
I did some research and turns out my gpu supports opengl 4.6, opengl's latest version is 4.6, can anyone send me vivcraft  build without this gpu block, idc if it crashes if not compatible.

My gpu is intel uhd graphics

My mail: barrulik@gmail.com

**Comment by TheTrueForce** [comment]
The OpenGL version involved is irrelevant. Intel's drivers malfunction with OpenGL in VR. Vivecraft displays that error message isntead of crashing with an obscure stacktrace.
An old version like one of the older 1.7.10 versions will probably not have the helpful error message.

Besides this, I do not understand how you expect any sort of acceptable VR performance out of an integrated GPU. Even if it worked, performance would be unacceptably bad.

**Comment by Nathan22211** [comment]
intel is coming out with dedicated gaming gpus, that's probably why
