### ISSUE TITLE
VR Issue

### ISSUE THREAD

**Issue by Lmorthian** [jrbudda/Vivecraft_117#5]
When I Launch Vivecraft It Lags Out My PC Like HELL. Also When Vivecaft Actually Loads Im Stuck In The Dirt Cube And Cannot Move My VR Hands. JrJubudda Could You Fix This Please?

**Comment by Techjar** [comment]
There is a known issue where the client lags a ton for a short time after startup. It's Mojang's fault, hopefully will be fixed in 1.18. In the meantime, having a strong CPU or allocating more memory can make it less laggy.

**Comment by Techjar** [comment]
Also, what is your system specs?
