### ISSUE TITLE
Movement is disabled when hands are in a block/flowing water

### ISSUE THREAD

**Issue by DimkaAkuma** [jrbudda/Vivecraft_117#6]
Vivecraft 1.17.1 Beta - When player hand is in a block, the movement/turning controls stop working. Like when Left hand is sunk into a block - cant move,  when right  - cannot turn. Have to pull hands back to enable controls.  Also happens when being submerged or moved by flowing water.  Very gamebreaking. The problem with solid blocks and right hand happen not all the time(or not with any settings - as i tried to change settings and it disappeared for now). But having right hand in flowing water completely disables all right controller except for its position tracking, untill the hand is out of water.  Left hand is working without issues in flowing water. Using : Play Mode - Standing,  Free-Move Type:Controller, Weapon Collisions:Auto, Roomscale Jumping and  Climbing :ON.

**Comment by DimkaAkuma** [comment]
Edit: Deleted Gameplay: Contextual Interact keybind in SteamVR,  which I had on Left Grip - no more problem with flowing water.
Still, Climbing Claws, even if just held, but not activated stops all other input from controllers, when hands are in a block. Maybe it was implemented as a protection from falling off, when climbing? But its very inconvenient, and surely will make parkour courses  (like the one on the server I play on) impossible .

**Comment by Techjar** [comment]
It's not supposed to stop all input, only the buttons that the climb claws use.

**Comment by DimkaAkuma** [comment]
My climbing claws are bound to Grips, not triggers. I reworked my bindings long ago, untill 1.17.1 there were no issues. Now it really blocks ALL input, except Hand tracking( moving my hands) and buttons bound to climb - grips.

**Comment by Techjar** [comment]
Okay it's probably a bug then. Likely the logic I mentioned above got broken in a recent refactor.

**Comment by DimkaAkuma** [comment]
Tested with Triggers as main button - same thing. Hoping for a fix in next version and thanks for your time.

**Comment by Techjar** [comment]
Can you test the latest release of 1.16.5?

**Comment by DimkaAkuma** [comment]
yeah, surely. Gonna download and test now.

**Comment by Techjar** [comment]
I found the bug.

**Comment by DimkaAkuma** [comment]
Tested on latest 1.16.5  - same thing - other contols besides moving hands and using claws are disabled.

My older 1.16.4 (probably v6) has no problem

**Comment by Techjar** [comment]
Yeah.

**Comment by Techjar** [comment]
A patch will be released soon.
